### ISSUE TITLE
Izveidot word/doc failu SharePointā

### ISSUE THREAD

**Issue by edzya** [edzya/CompriZip#2]
Nepieciešams, lai vienlaicīgi varam strādāt pie dokumenta, linku uz dokumentu nosherojam komentāros

**Comment by edzya** [comment]
Sagatavots folderis un docx - https://rtucloud1.sharepoint.com/:w:/r/sites/RTUScheduleservice/Shared%20Documents/3_project_Compression/[CSZC_EZ_KS_RG_3_project.docx](https://rtucloud1.sharepoint.com/:w:/r/sites/RTUScheduleservice/Shared%20Documents/3_project_Compression/CSZC_EZ_KS_RG_3_project.docx?d=w2ff26f10c9644719ad3be7bb27d24988&csf=1&web=1&e=C5FRcL)?d=w2ff26f10c9644719ad3be7bb27d24988&csf=1&web=1&e=C5FRcL

**Comment by edzya** [comment]
@svinacienitajs @Kaspars-dev  lūdzu pārbaudiet piekļuves

**Comment by Kaspars-dev** [comment]
> @svinacienitajs @Kaspars-dev lūdzu pārbaudiet piekļuves

Nevar piekļūt "This site cant be reached"

Bet caur School outlook email var atvērt

**Comment by svinacienitajs** [comment]
[Bytebenders_Apraksts.docx](https://github.com/edzya/CompriZip/files/14822384/Bytebenders_Apraksts.docx)

For safety reasons iemetīšu šeit fizisko kopiju no musu visu informācijas, kas pagaidam ir
