### ISSUE TITLE
Dokumentā izveidot 1. daļu - Grupas aprakstu

### ISSUE THREAD

**Issue by edzya** [edzya/CompriZip#3]
I. Grupas apraksts
- Grupas nosaukums.
- Grupas locekļi.
Norādīt vārdus, uzvārdus, grupas numurus un studenta apliecības numurus
- Grupas vadītāja vārds un uzvārds.
Grupas vadītājs ir atbildīgs par pārskatu, pirmkodu augšupielādi ORTUS portālā, kā arī par
pienākumu un darba sadali starp grupas locekļiem.
- Problēmu risināšanas metodes.
Aprakstīt kādā veidā grupa plāno risinātradušās darba gaitā problēmas, piemēram, ko grupa darīs,
ja viens no locekļiem neizpildīs savus pienākumus: neizstrādās kodu, savlaicīgi neizvietos darba
rezultātus ORTUSā un t.t. Tādu problēmu risināšanas ceļi var būt dažādi, piemēram, palikušie
grupas biedri var pieņemt lēmumu izpildīt visu darbu, vai izslēgt no grupas studentu, kas nestrādā.
Ievērojiet, ka visi pārskati un programmas kods pieder grupai.

**Comment by svinacienitajs** [comment]
[Bytebenders grupas apraksts.docx](https://github.com/edzya/CompriZip/files/14743033/Bytebenders.grupas.apraksts.docx)
[Bytebenders grupas apraksts.pdf](https://github.com/edzya/CompriZip/files/14743035/Bytebenders.grupas.apraksts.pdf)

Uzmetiet aci ludzu

**Comment by edzya** [comment]
Es domāju, ka nevajag tā pa pantiem un reliģiju pīt iekšā arī man liekas nebūtu labi.

Manuprāt, ja no kāda no grupas locekļiem nav inputs/outputs, tad pēc vairākiem brīdinājumiem vienkārši grupas biedru izslēdzam un neizdarītos darbus sadalām atlikušo grupas locekļu ietvaros.
@Kaspars-dev Tavas domas ?

**Comment by Kaspars-dev** [comment]
> Es domāju, ka nevajag tā pa pantiem un reliģiju pīt iekšā arī man liekas nebūtu labi.
> 
> Manuprāt, ja no kāda no grupas locekļiem nav inputs/outputs, tad pēc vairākiem brīdinājumiem vienkārši grupas biedru izslēdzam un neizdarītos darbus sadalām atlikušo grupas locekļu ietvaros. @Kaspars-dev Tavas domas ?

Arī domāju, ka nevajag reliģiju.
+
Es domāju vajadzētu varbūt izcelt vai arī jaunā rindā panta subtitle jeb apakštitulu, jo ne tik labi lasās.
Piemēram, 
**1. pants: Mērķis** 
Šī darba sodīšanas mērķis ir veicināt sadarbību un novērst uzdevumu
izpildīšanu komandās, ieviešot soda sankciju tiem, kuri neizpilda savus pienākumus komandu
darbā.

**Comment by svinacienitajs** [comment]
[Bytebenders grupas apraksts.docx](https://github.com/edzya/CompriZip/files/14759787/Bytebenders.grupas.apraksts.docx)
[Bytebenders grupas apraksts.pdf](https://github.com/edzya/CompriZip/files/14759788/Bytebenders.grupas.apraksts.pdf)

Updated versija:
(Izņēmu reliģiju)
(Formatēju)

**Comment by edzya** [comment]
Šī darba sodīšanas mērķis ir veicināt sadarbību un novērst uzdevumu izpildīšanu komandās - te nav kaut kāda loģiskā kļūda ? :D Veicināt sadarbību un novērst uzdevumu izpildīšanu komandās? Tā kā pretrunīgi sanāk

**Comment by edzya** [comment]
būs obligāta **izraidšana** - kļūda tekstā. 2. panta b punkta teikumam beigās nav pieturzīme.

>  4. pants: Sankciju īstenošana
> (a) Nespēja ievērot šā likumdošanas prasības var rezultēt papildu disciplinārās sankcijas, kā
> noteikts atbilstošajā organizācijā vai institūcijā.

šito man liekas ņemam ārā. 3 punkts jau ir īstenošana un pats pants nav saprotams.

**Comment by svinacienitajs** [comment]
Final piece


[Bytebenders grupas apraksts.docx](https://github.com/edzya/CompriZip/files/14822066/Bytebenders.grupas.apraksts.docx)
