### ISSUE TITLE
Dokumentā izveidot 2. daļu - Izvēlētās tehnoloģijas

### ISSUE THREAD

**Issue by edzya** [edzya/CompriZip#4]
II. Izvēlētās tehnoloģijas
- Komunikācijas metodes.
Aprakstīt, kā notiks komunikācija starp grupas locekļiem un cik bieži grupas locekļiem ir jāsazinās
ar grupas vadītāju un savā starpā, lai atskaitītos par darba progresu (telefonu zvani, SMS, e-pasta
vēstules, Viber, WhatsApp...; katru dienu vai vienu reizi nedēļā...).
- Izstrādes vides un versiju kontroles sistēmas (replit.com, GitHub.com, Bitbucket.org)

**Comment by Kaspars-dev** [comment]
Pievienoju word documentu.

Pārbaudiet vai ir ok
[2. Daļa Izvēlētās Tehnoloģijas.docx](https://github.com/edzya/CompriZip/files/14748065/2.Dala.Izveletas.Tehnologijas.docx)

**Comment by svinacienitajs** [comment]
Bļin , netīšam izdzēsu komentu šeit, sajuka ar savējo darbu, sorr kaspar

Bet par dokumentu, informācijas ziņa istās pretty ok, tavs skats @edzya ?

**Comment by Kaspars-dev** [comment]
[2. Daļa Izvēlētās Tehnoloģijas.docx](https://github.com/edzya/CompriZip/files/14764747/2.Dala.Izveletas.Tehnologijas.docx)
