### ISSUE TITLE
3. daļa - saspiešanas metodes

### ISSUE THREAD

**Issue by edzya** [edzya/CompriZip#5]
**III. Saspiešanas metožu apraksts**
Projekta ietvaros katrai grupai ir jāizstrādā programmu, kas var saspiest un dekodēt saspiestu failu.
Izpētiet eksistējošas datu saspiešanas metodes, katram komandas dalībniekam ir jāsameklē sekojošu
informāciju par vismaz vienu metodi (atrasto informāciju iekļaut pārskatā, metodes starp komandas
dalībniekiem sadala komandas vadītājs):
- Metodes nosaukums
- Vispārējās ziņas par algoritmu
Kāda tipa failiem un datiem algoritmu var pielietot (teksts, grafika,...), pie kuras saspiešanas
metožu saimes algoritms pieder (Dictionary, Variable-length codes, Run length encoding,...).
- Informācijas avotu saraksts
Atrast minimums divus informācijas avotus par izvēlēto saspiešanas metodi (grāmatas vai Web
vietnes). Īsi aprakstīt, kādu lietderīgu informāciju satur katrs no avotiem (uzrakstīt no 70 līdz 200
vārdus par katru no atrastiem informācijas avotiem).

**Comment by edzya** [comment]
Mums jāvienojas kurš kādu metodi pētīs.

**Comment by edzya** [comment]
> 
> For HTML files, which often contain repetitive patterns such as markup tags, text, and structure, algorithms that excel at handling redundancy and patterns tend to perform well. In this case, algorithms like LZMA and Bzip2 are good candidates for achieving the best compression ratios, as they are capable of efficiently compressing data with repetitive patterns, which are common in HTML files.
> 
> Both LZMA and Bzip2 are known for their ability to handle text data effectively, especially when the data has predictable patterns like HTML markup. These algorithms can analyze the structure and content of HTML files to find repetitive sequences and encode them more efficiently, resulting in better compression ratios.
> 
> While LZMA typically offers slightly better compression ratios compared to Bzip2, both algorithms are excellent choices for compressing HTML files when speed is not a concern. Since you've specified that speed is not important, you can prioritize compression ratio, making LZMA or Bzip2 suitable choices for your needs.
> 

Es paņemšu papētīt to LZMA algoritmu.

Lektore teica, ka deflate algoritms tika izmantoja tās iepriekšējās komandas, varbūt to vēl varam izpētīt un tad vajag vēlvienu. @Kaspars-dev  @svinacienitajs  ko sakiet ?

**Comment by svinacienitajs** [comment]
Es tad paņemšu paskatīšos to deflate

**Comment by edzya** [comment]
@Kaspars-dev ko Tu paņemsi ?

**Comment by Kaspars-dev** [comment]
> [@Kaspars-dev](https://github.com/Kaspars-dev) ko Tu paņemsi ?

Sorry ka tik ilgi aizņēmu, lai atbildētu,

Es varētu paņemt - _**PPMd algorithm**_
