### ISSUE TITLE
Deflate algoritms

### ISSUE THREAD

**Issue by edzya** [edzya/CompriZip#7]
- Metodes nosaukums
- Vispārējās ziņas par algoritmu
Kāda tipa failiem un datiem algoritmu var pielietot (teksts, grafika,...), pie kuras saspiešanas
metožu saimes algoritms pieder (Dictionary, Variable-length codes, Run length encoding,...).
- Informācijas avotu saraksts
Atrast minimums divus informācijas avotus par izvēlēto saspiešanas metodi (grāmatas vai Web
vietnes). Īsi aprakstīt, kādu lietderīgu informāciju satur katrs no avotiem (uzrakstīt no 70 līdz 200
vārdus par katru no atrastiem informācijas avotiem).

**Comment by svinacienitajs** [comment]
[Deflate-dokuments.docx](https://github.com/edzya/CompriZip/files/14805046/Deflate-dokuments.docx)

Es sarakstiju savu informāciju, ko sapratu un cerams, kad padosiet ziņu par kļūdām, jo ir iespejā kad tur būs kautkāda. @edzya @Kaspars-dev
